In [2]:
import torch 
from torch.autograd import Variable

In [3]:
x = Variable(torch.Tensor([2]),requires_grad=True)
y = x + 2
z = y ** 2 + 3
print(z)

tensor([19.], grad_fn=<AddBackward>)


In [ ]:
z.backward()

In [6]:
print(x.grad)

tensor([8.])


In [7]:
x = Variable(torch.Tensor([[1, 2], [3, 4]]), requires_grad=True)
y = Variable(torch.Tensor([[4], [5]]), requires_grad=True)

In [11]:
z = torch.mean(torch.matmul(x, y))

In [12]:
z.backward()
print(x.grad)

tensor([[2.0000, 2.5000],
        [2.0000, 2.5000]])


In [13]:
print(y.grad)

tensor([[2.],
        [3.]])


In [14]:
m = Variable(torch.FloatTensor([[2, 3]]), requires_grad=True)
n = Variable(torch.zeros(1, 2))
print(m)
print(n)

tensor([[2., 3.]], requires_grad=True)
tensor([[0., 0.]])


In [15]:
n[0, 0] = m[0, 0] ** 2
n[0, 1] = m[0, 1] ** 3
print(n)

tensor([[ 4., 27.]], grad_fn=<CopySlices>)


In [18]:
n.backward(torch.ones_like(n))
print(m.grad)

tensor([[ 4., 27.]])


In [20]:
x = Variable(torch.FloatTensor([3]), requires_grad=True)
y = x * 2 + x ** 2 + 3

In [21]:
y.backward(retain_graph=True)

In [22]:
x.grad

tensor([8.])

In [23]:
y.backward()

In [24]:
x.grad

tensor([16.])

In [29]:
x = Variable(torch.FloatTensor([2, 3]), requires_grad=True)
k = Variable(torch.zeros(2))

In [30]:
k[0] = x[0]**2 + 3* x[1]
k[1] = x[0] * 2+ x[1] ** 2

In [34]:
j = torch.zeros(2, 2)
k.backward(torch.FloatTensor([1, 0]), retain_graph=True)

In [35]:
j[0] = x.grad.data

In [38]:
x.grad.data.zero_()

tensor([0., 0.])

In [39]:
k.backward(torch.FloatTensor([0, 1]))
j[1] = x.grad.data

In [40]:
print(j)

tensor([[4., 3.],
        [2., 6.]])
