In [2]:
import torch 
import numpy as np

In [3]:
numpy_tensor = np.random.randn(10, 20)

In [4]:
pytorch_tensor1 = torch.Tensor(numpy_tensor)
pytorch_tensor2 = torch.Tensor(numpy_tensor)

In [5]:
numpy_array = pytorch_tensor1.numpy()
numpy_array = pytorch_tensor1.cpu().numpy()

In [6]:
dtype = torch.cuda.FloatTensor
gpu_tensor = torch.randn(10, 20).type(dtype)

gpu_tensor = torch.randn(10, 20).cuda(0)
gpu_tensor = torch.randn(10, 20).cuda(1) ## 只有一个 GPU 吗？

RuntimeError: CUDA error (10): invalid device ordinal

In [7]:
cpu_tensor = gpu_tensor.cpu()

In [8]:
print(pytorch_tensor1.shape)
print(pytorch_tensor2.size())

torch.Size([10, 20])
torch.Size([10, 20])


In [9]:
print(pytorch_tensor1.dim())

2


In [11]:
print(pytorch_tensor1.numel())

200


In [12]:
x = torch.randn(3, 2)
x = x.type(torch.DoubleTensor)
x_array = x.numpy()
print(x_array.dtype)

float64


In [16]:
 x = torch.ones(2, 2)

In [18]:
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [19]:
print(x.type())

torch.FloatTensor


In [20]:
x = x.long()

In [21]:
print(x)

tensor([[1, 1],
        [1, 1]])


In [22]:
x = x.float()

In [24]:
print(x.type())

torch.FloatTensor


In [25]:
x = torch.randn(4, 3)
print(x)

tensor([[ 0.0803,  1.0962,  0.2946],
        [-1.1253,  0.7358,  0.4558],
        [-0.6849,  0.9953, -0.1609],
        [-0.6374, -0.9429,  1.1899]])


In [26]:
torch.max(x, dim=1)

(tensor([1.0962, 0.7358, 0.9953, 1.1899]), tensor([1, 1, 1, 2]))

In [27]:
torch.sum(x, 1)

tensor([ 1.4711,  0.0663,  0.1494, -0.3904])

In [28]:
print(x.shape)
x = x.unsqueeze(0) # 在第一维度增加
print(x.shape)

torch.Size([4, 3])
torch.Size([1, 4, 3])


In [29]:
x = x.unsqueeze(1)
print(x.shape)

torch.Size([1, 1, 4, 3])


In [31]:
x = x.squeeze()

In [32]:
x.shape

torch.Size([4, 3])

In [35]:
x = torch.randn(4, 3, 5)
print(x.shape)
x = x.permute(1, 0, 2)
print(x.shape)
x = x.transpose(0, 2)
print(x.shape)

torch.Size([4, 3, 5])
torch.Size([3, 4, 5])
torch.Size([5, 4, 3])


In [37]:
x = torch.randn(3, 4, 5)
print(x.shape)
x = x.view(-1, 5)
print(x.shape)
x = x.view(3, 20)
print(x.shape)

torch.Size([3, 4, 5])
torch.Size([12, 5])
torch.Size([3, 20])


In [42]:
x = torch.ones(4, 4).float()
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [43]:
x[1:3, 1:3] = 2

In [44]:
x

tensor([[1., 1., 1., 1.],
        [1., 2., 2., 1.],
        [1., 2., 2., 1.],
        [1., 1., 1., 1.]])

In [45]:
from torch.autograd import Variable

In [48]:
x_tensor = torch.randn(10, 5)
y_tensor = torch.randn(10, 5)

x = Variable(x_tensor, requires_grad=True)
y = Variable(y_tensor, requires_grad=True)

In [50]:
z = torch.sum(x + y)

In [51]:
print(z.data)
print(z.grad_fn)

tensor(12.6318)


In [52]:
z.backward()
print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [53]:
x = torch.Tensor([2])

In [55]:
x = Variable(x, requires_grad=True)

In [57]:
y = x**2
y.backward()

In [58]:
print(x.grad)

tensor([4.])
